### PR TITLE
Fixes transfers to File when `append?` is true

### LINKED ISSUE #23: {:append? true} is ignored on Mac, but not Linux
The `transfer` function accepts an options map, and one option that's accepted when the output is a file is `:append?`, which defaults to `true`. That option is supposed to be used at https://github.com/ztellman/byte-streams/blob/a7706c1/src/byte_streams.clj#L571-L573 and indeed it seems to work when run on a Linux machine. However, when the same code is run on a macbook, this option seems to do nothing: setting it to `true`, or `false`, or not specifying it at all, all result in the output file being clobbered and overwritten with the new contents. 

Below is some sample clojure code you can run to reproduce this issue, expressed as a clojure.test `deftest`; after loading this namespace, you can simply run `(append-works)` to check for correct behavior. On Mac OS, one test fails; on Linux, they all pass.

Note that this uses `./test.txt` as a scratch file, so if you have something important in this location there is some risk to running the tests. I've included a bail-out clause at the beginning to avoid that, but just in case it's probably best not to rely on that, and instead make sure that no such file exists before running the test.

``` clj
(ns amalloy.test-byte-streams
  (:require [byte-streams :as bs]
            [clojure.java.io :as io]
            [clojure.test :refer [deftest is]])
  (:import (java.io FileOutputStream)
           (java.nio ByteBuffer)))

(def text (.getBytes "abcd"))
(def file (io/file "test.txt"))

(defn contents []
  (slurp file))

(deftest append-works
  (when (.exists file) (throw (RuntimeException. "Refusing to delete existing test.txt file")))
  (bs/transfer text file)
  (is (= "abcd" (contents)) "transferring to deleted file failed")
  (bs/transfer text file {:append? false})
  (is (= "abcd" (contents)) "overwriting with :append? false failed")

  (bs/transfer text file {:append? true})
  (is (= "abcdabcd" (contents)) "appending same contents with :append? true failed")

  (bs/transfer text file {:append? false})
  (is (= "abcd" (contents)) "overwriting with :append? false failed")

  (with-open [out-chan (.getChannel (FileOutputStream. file true))]
    (.write out-chan (ByteBuffer/wrap text)))
  (is (= "abcdabcd" (contents)) "appending by hand with java.nio failed")

  (.delete file))
```

### PR DESCRIPTION
**Pull request by KingMob**
Fixes #23...I think.

I have no idea why it would have worked on Linux, but not a Mac. I believe append-mode for File transfers should have been broken for all platforms, except when "appending" to empty files.

The current fix calls .position() on the FileChannel to know where to start. Normally a fresh FC will be at 0, except in append mode, when .position() will always return the current size of the file.

This doesn't handle multiple writers correctly, since it never calls .position() again, but there's a lot more work to do to make byte-streams compatible with that assumption, so we're not tackling that here.

### CODE REVIEW

File: src/clj_commons/byte_streams.clj [hunk 1]
```diff
@@ -638,10 +635,11 @@
   [channel file {:keys [chunk-size] :or {chunk-size (int 1e7)} :as options}]
   (let [^FileChannel fc (convert file WritableByteChannel options)]
     (try
-      (loop [idx 0]
-        (let [n (.transferFrom fc channel idx chunk-size)]
-          (when (pos? n)
-            (recur (+ idx n)))))
+      ;; .position() is 0 for normal mode, and the current size of the file in append mode
+      (loop [pos (.position fc)]
```
Comment (arnaudgeiser) [inline src/clj_commons/byte_streams.clj:639]: Tests are passing without this modification.
Without a deep knowledge of byte-streams, I'm wondering whether we are acting at the right place here.
If I understand correctly, the position defines where on the `ReadableByteChannel` has to start, not on the `ẀriteableByteChannel`. [1]

But I might be totally wrong here.

[1] : https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/nio/channels/FileChannel.html#transferFrom(java.nio.channels.ReadableByteChannel,long,long)

Comment (KingMob) [reply src/clj_commons/byte_streams.clj:639]: I’ll double-check, but the new tests were failing on my Mac. The original issue claimed it didn’t happen on Linux…is that your platform?

Comment (KingMob) [reply src/clj_commons/byte_streams.clj:639]: It’s the reverse about the position. It defines where in the FC to start writing, regardless of the FC’s current position. The RBC’s position advances normally as data is read. 

If the transferFrom fn used the FC position, append mode would work by default. 

That being said, I’m concerned that it may be platform-specific, because that means CI may miss a regression.

Comment (KingMob) [reply src/clj_commons/byte_streams.clj:639]: I reverted it, and my tests failed again.

Comment (arnaudgeiser) [reply src/clj_commons/byte_streams.clj:639]: > I’ll double-check, but the new tests were failing on my Mac. The original issue claimed it didn’t happen on Linux…is that your platform?

Yes it is, but I got caught be your comment:

>  I believe append-mode for File transfers should have been broken for all platforms, except when "appending" to empty files.

So I confirm, it's working on Linux with and without your change.

**Review by arnaudgeiser — APPROVED** [review]
Perfect then!

File: src/clj_commons/byte_streams.clj (hunk 1 above)
Comment (KingMob) [reply src/clj_commons/byte_streams.clj:639]: That’s crazy. I wonder if we discovered a Linux jdk bug. Which Java version did you test on?

the Java code quickly hands off to native code, nothing I saw would explain this.

Comment (arnaudgeiser) [reply src/clj_commons/byte_streams.clj:639]:
```
❯ java -version
openjdk version "17.0.1" 2021-10-19
OpenJDK Runtime Environment Temurin-17.0.1+12 (build 17.0.1+12)
OpenJDK 64-Bit Server VM Temurin-17.0.1+12 (build 17.0.1+12, mixed mode, sharing)
```

Comment (arnaudgeiser) [reply src/clj_commons/byte_streams.clj:639]: Maybe the `getChannel` is behaving differently according to the platform.

[1] : https://github.com/clj-commons/byte-streams/blob/master/src/byte_streams.clj#L589

Comment (KingMob) [reply src/clj_commons/byte_streams.clj:639]: Yeah, that's pretty likely, but I couldn't find anything online about it. I looked at the underlying FileChannelImpl class, and it dispatches a bunch to native-based FileDescriptors and FileDispatcher classes.

I can try more variations in the tests. Maybe fill it with data first, then close and reopen, to ensure we're not starting with an empty file.
